[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
eleven = "EgRFKeAiDc9GjGH1sWaPFzMwh39t3yDP2Fyo8dKNdM4B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
